version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    labels:
      - 📦 dependencies
    directory: "/"
    commit-message:
      prefix: "chore(deps)[github-actions]"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    labels:
      - 📦 dependencies
    directory: "/"
    commit-message:
      prefix: "chore(deps)[npm]"
    schedule:
      interval: "weekly"
